config/routes.rb
Rails.application.routes.draw do
resources :users, only: [:show, :new, :create, :edit, :update, :destroy] 
resources :teams
resources :tasks do
    member do
        patch :completed
    end
end
resources :projects
resources :comments, only: [:show, :new, :create]
resources :userteams, only: [:new, :create, :destroy]
  
get "/", to: "users#home", as: "home"
get "/login", to: "sessions#login"
post "/login", to: "sessions#process_login"
get "/logout", to: "sessions#logout"

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project, optional: true
    belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
    belongs_to :assignee, :class_name => 'User', :foreign_key => 'assignee_id', optional: true
    has_many :comments 

    validates :creator_id, presence: true 
    validates :description, presence: true

    validates :priority, presence: true 
    validates :priority, acceptance: { accept: ['High', 'Medium', 'Low'] }

    validates :status, presence: true 
    validates :status, acceptance: { accept: ['Planned', 'In Progress', 'Complete'] }

    validates :due_date, presence: true 



    #method that udpates the status to COMPLETE, not in use yet
    # def set_project_task_to_complete
    #     self.status = "Complete"
    # end 

    # #method that udpates the status to IN PROGRESS, not in use yet
    # def set_to_in_progress
    #     self.status = "In Progress"
    #     redirect_to task_path 
    # end 

    def completed?
        !date.blank?
    end
    #check if self.status == "Complete"
    #if true print done
    #if false 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorized
  before_action :set_task, only: [:show, :edit, :update, :completed, :destroy]

  def index
    @ordered_tasks = Task.where(:assignee_id => current_user).order("due_date")
    @completed_tasks = @ordered_tasks.select{|task| task.date != nil}
    @incomplete_tasks = @ordered_tasks.select{|task| task.date == nil}
    @task = Task.new
  end

  def show
    @comment = Comment.new 
    @task_comments = Comment.all.where(task_id: @task.id).order("created_at DESC")
  end

  def new
    @task= current_user.created_tasks.build 
  end

  def create
    @task= current_user.created_tasks.build(task_params)
    if @task.valid?
      @task.save
      
      if @task.created_location == "project" 
          redirect_to project_path(@task.project_id)
      elsif 
          @task.created_location.nil?
          redirect_to task_path(@task.id)
      # #if created from USER page, reload USER page after task creation
        else
          redirect_to tasks_path
        end 
    else
      render :new
    end 
  end

  def edit
  end 

  def update
    @task.update(task_params)
    if @task.valid?
      @task.save
      redirect_to task_path(@task.id)
    else 
      render :edit 
    end 
  end 

  def completed
    @task.update(date: Date.today, status: "Complete")
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end


  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params 
    params.require(:task).permit(:project_id, :creator_id, :assignee_id, :priority, :description, :due_date, :status, :created_location)
  end 



end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_comment_form.html.erb
<%=render partial: "shared/error_messages", locals: {new_object: @comment}%>

<%= bootstrap_form_for(@comment, layout: :inline) do |f| %>
    <%= f.text_area :comment, hide_label: true  %>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :task_id, value: @task.id %>
    <br></br>
    <p><%= f.submit "Post", class: "btn btn-primary"  %> </p>

<% end %>

app/views/tasks/_task_form.html.erb
<%=render partial: "shared/error_messages", locals: {new_object: @task}%>

<br>

<%= bootstrap_form_for(@task,:class => "form-inline", label_errors: true) do |f| %>
        
        <%= f.text_field :description, placeholder: "Description" %>

        <%= f.date_field :due_date %>

        <%= f.collection_select(:project_id, Project.all, :id, :name, {include_blank: true}) %>
        
        <%= f.collection_select(:assignee_id, User.all, :id, :name, {selected: current_user.id}) %>

        
        <%= f.select :priority, options_for_select([ "Low", "Medium", "High"]) %>

        
        <%= f.select :status, options_for_select(["Planned", "In Progress", "Complete"]) %>


        <p><%= f.submit "Submit", class: "btn btn-primary" %> </p>
        


<% end %>

app/views/tasks/blank.html.erb
<div class="col-md-8">
<%if @ordered_tasks == []%>
 <div> <%= current_user.name%> does not have any tasks at this time. </div>
<%else%>
<br>
<table class="table table-hover">
  
  <thead>
      <tr>
      
          <th>Project</th>
          <th>Task</th>
          <th>Due Date</th>
          <th>Status</th>
          <th>Complete</th>
          <th>Edit</th>
          <th>Delete</th>
      </tr>
  </thead>
  
  
  <tbody>
      <%@ordered_tasks.each do |task|%>
      <tr>
          <%if task.completed?%>
              
              <td><%if !@task.project.nil?%> <%= link_to task.project.name, project_path(@task.project.id) %><%end%></td>
              <td><s><%=link_to task.description, task_path(task)%></s></td>
              <td><%=task.due_date%></td>
              <td><%=task.status%></td>
              <td> <%=fa_icon("check")%></td>
              <td><%=link_to edit_task_path(task) do %>
                      <%= fa_icon("edit") %>
                      <%end%></td>
              <td><%=link_to task_path(task), method: :delete, data: {confirm: "Are you sure?"} do %>
                      <%= fa_icon("trash-alt") %>
                      <%end%></td>
          <%else%>
              <td><% if task.project.nil?%>
                  <%= "n/a"%>
              <%else%>
                  <%=link_to task.project.name, project_path(task.project)%>
              <%end%></td>
              <td><%=link_to task.description, task_path(task)%></td>
              <td><%=task.due_date%></td>
              <td><%=task.status%></td>
              <td><%=link_to completed_task_path(task), method: :patch do %>
                      <%= fa_icon("square", type: :regular) %>
                      <%end%></td>
              <td><%=link_to edit_task_path(task) do %>
                      <%= fa_icon("edit") %>
                      <%end%></td>
              <td><%=link_to task_path(task), method: :delete, data: {confirm: "Are you sure?"} do %>
                      <%= fa_icon("trash-alt") %>
                      <%end%></td>
                  
          <%end%>
      </tr>
      <%end%>
  </tbody>
</table>

<%end%>
</div>



</div>

</div>

app/views/tasks/edit.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>EDIT</h1>
    <p class="lead">Sometimes things change. </p>
</div>
<div class="col-md-4">
    <h2><%= @task.description %></h2>
    <br>
    <%=render "task_form"%>
</div>
<div class="col-md-3">
</div>
<div class="col-md-2"></div>
</div>

app/views/tasks/index.html.erb
<div class="container">
<div class="row justify-content-start">
  
  <div class="text-center">
  <div class="col-md-4">
  <div class="text-right">
  
      <h1>Tasks</h1>
  </div>
  <br>
<div>
  <h4>Create A New Task</h4>
  <%=render "task_form"%>
  </div>

</div>
</div>

<div class="col-md-8">



<h4>INCOMPLETE </h4>


<% if @incomplete_tasks == [] %>
 <i> <%= current_user.name%> does not have any tasks at this time. </i>
<% else %>
<table class="table">
      <thead>
          <tr>
          <th>Project</th>
          <th>Task</th>
          <th>Due Date</th>
          <th>Status</th>
          <th>Complete</th>
          <th>Edit</th>
          <th>Delete</th>
          </tr>
      </thead>

      <tbody>
      <% @incomplete_tasks.each do |task| %>
          <tr>
                <td><% if task.project.nil?%>
                    <%= "n/a"%>
                <%else%>
                    <%=link_to task.project.name, project_path(task.project)%>
                <%end%></td>
                <td><%=link_to task.description, task_path(task)%></td>
                <td><%=task.due_date%></td>
                <td><%=task.status%></td>
                <td><%=link_to completed_task_path(task), method: :patch do %>
                        <%= fa_icon("square", type: :regular) %>
                        <%end%></td>
                <td><%=link_to edit_task_path(task) do %>
                        <%= fa_icon("edit") %>
                        <%end%></td>
                <td><%=link_to task_path(task), method: :delete, data: {confirm: "Are you sure?"} do %>
                        <%= fa_icon("trash-alt") %>
                        <%end%></td>
          </tr>
      <% end %> 
      </tbody>
      </table>

  <% end %>



  <br></br>


  
<% if @completed_tasks != [] %>
<h4>COMPLETE</h4>


<table class="table">
    <thead>
      <tr>
            <th>Project</th>
            <th>Task</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Complete</th>
            <th>Edit</th>
            <th>Delete</th>
      </tr>
    </thead>

    <tbody>
    <% @completed_tasks.each do |task| %>
        <tr>
            <td><% if task.project.nil?%>
                    <%= "n/a"%>
                <%else%>
                    <%=link_to task.project.name, project_path(task.project)%>
                <%end%></td></td>
            <td><s><%=link_to task.description, task_path(task)%></s></td>
            <td><%=task.due_date%></td>
            <td><%=task.status%></td>
            <td> <%=fa_icon("check")%></td>
            <td><%=link_to edit_task_path(task) do %>
                    <%= fa_icon("edit") %>
                    <%end%></td>
            <td><%=link_to task_path(task), method: :delete, data: {confirm: "Are you sure?"} do %>
                    <%= fa_icon("trash-alt") %>
                    <%end%></td>
        </tr>
    <% end %> 
  </tbody>
  </table>
<% end %> 





</div>

app/views/tasks/new.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>NEW TASK</h1>
    <p class="lead">Plan your <b>work</b>. <br><b>Work</b> your plan. </p>
</div>
<div class="col-md-4">
    <h2><%= @task.description %></h2>
    <br>
    <%=render "task_form"%>
</div>
<div class="col-md-3">
</div>
<div class="col-md-2"></div>
</div>

app/views/tasks/show.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>Task</h1>
    <p class="lead">Have you finished this task? </p>

    <p><%= link_to "Mark Complete", completed_task_path, :method => :patch, class: "btn btn-primary" %> </p>



</div>
<div class="col-md-4">


    <h2><%= @task.description %></h2>
    <br>
    <div><%= link_to "Edit", edit_task_path(@task) %> | <%= link_to 'Delete', @task, method: :delete, data: { confirm: 'Are you sure?' } %>  <%if !@task.project.nil?%>| <%= link_to "Return to Project", project_path(@task.project.id) %><%end%></div>
    </br>

    <table class="table">
        <tr>
            <td>Assigned to:</td>
            <td> <%= link_to @task.assignee.name, user_path(@task.assignee.id) %></td>
        </tr>
        <tr>
            <td>Status:</td>
            <td><%= @task.status %></td>
        </tr>
        <tr>
            <td>Priority:</td>
            <td><%= @task.priority %></td>
        </tr>
        <tr>
            <td>Due:</td>
            <td><%= @task.due_date %></td>
        </tr>
        <tr>
        <td>Completed:</td>
        <td><%= @task.date %></td>
    </tr>
        <tr>
            <td>Project: </td>
            <td><%if !@task.project.nil?%><%= link_to @task.project.name, project_path(@task.project.id) %><%end%></td>
        </tr>
        <tr>
            <td>Created by:</td>
            <td><%= link_to @task.creator.name, user_path(@task.creator.id) %></td>
        </tr>


    </table>



</div>


<div class="col-md-3">
    <h3>COMMENT</h3>
    <p class="lead">Any updates on this task? </p>

    <%=render "comment_form"%>
    </br>
    <h3>ACTIVITY</h3>

        <% if @task_comments == [] %> 
        <p class="lead">There are no comments on this task. Write one above!</p>

        <% else %>
            <div>
                <% @task_comments.each do |c| %>
                    <div>____________________________________</div>
                    <div><b><%= link_to "@" + c.user.name, user_path(c.user.id) %></b> | <%= distance_of_time_in_words(c.created_at, Time.now, include_seconds: false) %> ago </div> 
                    </br>
                    <div> <%= c.comment %> </div>

                <% end %> 
            </div>
        <% end %>

    </br>



</div>

<div class="col-md-2"></div>
</div>