config/routes.rb
Rails.application.routes.draw do
resources :users, only: [:show, :new, :create, :edit, :update, :destroy] 
resources :teams
resources :tasks do
    member do
        patch :completed
    end
end
resources :projects
resources :comments, only: [:show, :new, :create]
resources :userteams, only: [:new, :create, :destroy]
  
get "/", to: "users#home", as: "home"
get "/login", to: "sessions#login"
post "/login", to: "sessions#process_login"
get "/logout", to: "sessions#logout"

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :userteams, dependent: :destroy
    has_many :teams, through: :userteams
    
    has_many :created_tasks, :class_name => 'Task', :foreign_key => 'creator_id', dependent: :destroy
    # has_many :creators, through: :created_tasks, source: :creator

    has_many :assigned_tasks, :class_name => 'Task', :foreign_key => 'assignee_id', dependent: :destroy
    # has_many :assignees, through: :assigned_tasks, source: :assignee 
    
    has_many :projects, through: :created_tasks
    has_many :projects, through: :assigned_tasks
    has_many :comments 

    validates :name, presence: true
    validates :age, presence: true
    validates :username, presence: true, uniqueness: {case_sensitive: false}
    

   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorized, except: [:new, :create, :home]
  before_action :user_finder, only: [:show, :edit, :update]
  
  def show
    @ordered_tasks = @user.assigned_tasks.order("due_date")
    @task = Task.new
    @user_teams = current_user.teams
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
      @user.save 
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    User.destroy(params[:id])
    redirect_to home_path
  end

  def home
    
  end

  private

  def user_finder
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :age, :bio, :username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_logged_in_home.html.erb
<div class="container-fluid"> 
    <div class="row text-center">
        <div class="col-md-12 col-sm-12 banner">
            
            <h2>Welcome to Team Task</h2>
            <p>Where we make project management, managable.</p>
                <button><%=link_to "View Tasks", tasks_path%></button>
                <button><%=link_to "View Projects", projects_path%></button>
        </div
    </div>
</div>

app/views/users/_logged_out_home.html.erb
<div class="container-fluid"> 
    <div class="row text-center">
        <div class="col-md-12 col-sm-12 banner">
            <h2>Welcome to Team Task</h2>
            <p>Where we make project management, managable.</p>
                <button><%=link_to "Sign Up", new_user_path%></button>
                <button><%=link_to "Login", login_path%></button>
        </div
    </div>
</div>

app/views/users/_user_form.html.erb
<%=render partial: "shared/error_messages", locals: {new_object: @user} %>

<%=bootstrap_form_for @user do |t|%> 
    <%=t.text_field :name%><br>
    <%=t.text_field :age%><br>
    <%=t.text_area :bio%><br>
    <%=t.text_field :username%><br>
    <%=t.password_field :password%>

    <%=t.submit "Submit", class: "btn btn-primary" %>  
<%end%>

app/views/users/edit.html.erb
<div class="container-fluid"> 
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            
            <h2>Edit User</h2>
            <p>Where we make project management, managable.</p></br>
            <%=render "user_form"%> 
        </div>
        <div class="col-md-4"></div>


    </div>
    <div class="row">
    </div>
</div>

app/views/users/home.html.erb
<%if current_user.nil?%>

    <%= render "logged_out_home"%>

<%else%>

    <%=render "logged_in_home"%>

<%end%>

app/views/users/new.html.erb
<div class="container-fluid"> 
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            
            <h2>Create a New Account</h2>
            <p>Where we make project management, managable.</p></br>
            <%=render "user_form"%> 
        </div>
        <div class="col-md-4"></div>


    </div>
    <div class="row">
    </div>
</div>

app/views/users/show.html.erb
    
    <div class="col-md-6 col-md-offset-3">
    <div class="jumbotron">
    <div class="text-center">
        <div class="row">
        <div class="col-md-8">
            <div class="profile">
                <img src="https://picsum.photos/200" >
            </div>
        </div>
        <div class="text-left">
        <div class="col-md-4">
            <h1><%=@user.name%></h1>
            <div class="lead"><%=@user.bio%></div>
            <div>Age: <%=@user.age%></div>

            <%if @user.teams != nil && @user == current_user%>
                <br><h4><%= link_to "Team(s):", teams_path%> </h4>
                <ul><h5><%@user_teams.each do |team| %>
                    <li><%= link_to team.name, team_path(team)%></li>
                <%end%></h5></ul>
                    <%= link_to "Join A Team", new_userteam_path%><br>
    
            <%elsif @user.teams != nil%>
                <br><h4>Team(s):</h4>
                <ul><h5><%@user_teams.each do |team| %>
                    <li><%= team.name%></li>
                <%end%></h5></ul>
            <%end%>

            <%if current_user == @user%>
                <br>
                <%= link_to "View Current Tasks", tasks_path%><br>
                <%=link_to "Edit Profile", edit_user_path(@user)%><br>
                <%=link_to "Delete", user_path(@user), :method => :delete, data: {confirm: "Are you sure you want to delete your profile? We'd hate to see you go!"}%><br>
            <%end%>
        </div>
        </div>
    </div>
        



    </div>
    </div>