config/routes.rb
Rails.application.routes.draw do
resources :users, only: [:show, :new, :create, :edit, :update, :destroy] 
resources :teams
resources :tasks do
    member do
        patch :completed
    end
end
resources :projects
resources :comments, only: [:show, :new, :create]
resources :userteams, only: [:new, :create, :destroy]
  
get "/", to: "users#home", as: "home"
get "/login", to: "sessions#login"
post "/login", to: "sessions#process_login"
get "/logout", to: "sessions#logout"

end

app/models/project.rb
class Project < ApplicationRecord

    belongs_to :team, optional: true
    has_many :tasks, dependent: :destroy
    accepts_nested_attributes_for :tasks,
        reject_if: Proc.new {|attributes| attributes[:description].blank?}
    # has_many :creators, through: :tasks, source: :creator 
    # has_many :assignees, through: :tasks, source: :assignee_id 
    validates :name, presence: true 
    validates :start_date, presence: true 
    validates :end_date, presence: true 
    validates :description, presence: true 
    validates :description, length: { minimum: 5 }

    validates :status, presence: true 
    validates :status, acceptance: { accept: ['Planned', 'In Progress', 'Complete'] }

    def project_count
        
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorized
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.where(:team_id => current_user.teams)

    @completed_projects = []
    @projects.each do |p|
      if p.status == "Complete"
        @completed_projects << p 
      end 
    end 

    @incomplete_projects = []
    @projects.each do |p|
      if p.status != "Complete"
        @incomplete_projects << p 
      end 
    end 
    @incomplete_projects = @incomplete_projects.sort_by {|p| p[:start_date]}
   

  end

  def show
     #separates out completed tasks 
    @completed_tasks = []
    @project.tasks.each do |t|
      if t.status == "Complete"
        @completed_tasks << t 
      end 
    end 

    #separates out incomplete tasks 
    @incomplete_tasks = []
    @project.tasks.each do |t|
      if t.status != "Complete"
        @incomplete_tasks << t 
      end 
    end 
    @incomplete_tasks = @incomplete_tasks.sort_by {|t| t[:due_date]}
    @task = Task.new 

  end

  def new
    @project = Project.new 
    @teams = current_user.teams
    
    3.times {@project.tasks.build}
  end

  def create
    @project = Project.new(project_params)
    if @project.valid?
      @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.valid?
      @project.save
      redirect_to project_path(@project)
    else 
      render :edit 
    end 
  end 

  def destroy
    
    @project.destroy
    redirect_to projects_path 
  end


  def complete
    @project = Project.find(params[:id])
    @project.update_attribute(:status, "Complete")
    @project.update_attribute(:completed_at, Time.now)
    redirect_to root_path 
  end 

  private 

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params 
    params.require(:project).permit(:name, 
      :start_date, 
      :end_date, 
      :description, 
      :team_id, 
      :status, 
        tasks_attributes: [
          :creator_id, 
          :assignee_id, 
          :priority, 
          :description, 
          :due_date, 
          :status, 
          :created_location])
  end 


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_form.html.erb
<%=render partial: "shared/error_messages", locals: {new_object: @project}%>

  <%= bootstrap_form_for(@project, layout: :inline) do |f| %>

  <table class="table">


  <tbody>
      <tr><td>Name</td><td><%= f.text_area :name, hide_label: true  %></td></tr>
      <tr><td>Start</td><td><%= f.date_field :start_date, hide_label: true  %></td></tr>
      <tr><td>End</td><td><%= f.date_field :end_date, hide_label: true  %></td></tr>
    <%if !@teams == []%>
      <tr><td>Team</td><td><%= f.collection_select(:team_id, current_user.teams, :id, :name, {hide_label: true, include_blank: true}) %></td></tr>
    <%end%>
      <tr><td>Status</td><td><%= f.select :status, options_for_select(["Planned", "In Progress", "Complete"]), {hide_label: true} %></td></tr>
      <tr><td>Description</td><td><%= f.text_area :description, hide_label: true  %></td></tr>
      <tr><td></td><td><%= f.submit "Create", class: "btn btn-primary"  %>  <%= link_to "Cancel", projects_path, class: "btn btn-danger" %> </td></tr>
    

        </tbody>
        </table>

  <% end %>

app/views/projects/_task_form.html.erb
<%=render partial: "shared/error_messages", locals: {new_object: @task}%>

<%= form_for @task do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :due_date %>
    <%= f.date_field :due_date %></br>

    <%= f.label :assigned_to %>
    <%= f.collection_select(:assignee_id, User.all, :id, :name) %>

    <%= f.label :priority %>
    <%= f.select :priority, options_for_select([ "Low", "Medium", "Hight"]) %>

    <%= f.label :status %>
    <%= f.select :status, options_for_select(["Planned", "In Progress", "Complete"]) %>

    
    <%= f.hidden_field :project_id, value: @project.id %>
    <%= f.hidden_field :creator_id, value: current_user.id %>
    <%= f.hidden_field :created_location, value: "project" %>

    <p><%= f.submit %> </p>

<% end %>

app/views/projects/edit.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>Projects</h1>
    <p class="lead"> Enter key project details and get started with a few tasks. </p>
</div>

<div class="col-md-6">

    <h3>Edit this Project</h3>

    <%=render "project_form"%>


</div>
<div class="col-md-3"></div>

app/views/projects/index.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>Projects</h1>
    <p class="lead"> Are you ready to start your next project?</p>

    <p><%= link_to "New Project", new_project_path, class: "btn btn-primary" %> 
    </p>
</div>
<div class="col-md-6">

<h3> Current </h3>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Status</th>
        <th>Team</th>
      </tr>
    </thead>

    <tbody>
    <% @incomplete_projects.each do |p| %>
        <tr>
        <td><%=  link_to p.name, project_path(p.id) %></td>
        <td><%=  p.start_date %></td>
        <td><%=  p.end_date %></td>
        <td><%=  p.status %></td>
        <td><%=  link_to p.team.name, team_path(p.team.id) %></td>
        </tr>
    <% end %> 
  </tbody>
  </table>

  <h3> Completed</h3>


  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th>Team</th>
    </tr>
  </thead>

  <tbody>
  <% @completed_projects.each do |p| %>
      <tr>
      <td><%=  link_to p.name, project_path(p.id) %></td>
      <td><%=  p.start_date %></td>
      <td><%=  p.end_date %></td>
      <td><%=  p.status %></td>
      <td><%=  link_to p.team.name, team_path(p.team.id) %></td>
      </tr>
  <% end %> 
</tbody>
</table>



</div>
<div class="col-md-3"></div>

app/views/projects/new.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-2">
    <h1>Projects</h1>
    <p class="lead"> Enter key project details and get started with a few tasks. </p>


</div>

<div class="col-md-6">

    <h3>Create a New Project</h3>

    <%=render "project_form"%>


</div>
<div class="col-md-3"></div>

app/views/projects/show.html.erb
<div class="row">
<div class="col-md-1"></div>
<div class="col-md-4">
      <h1><%= @project.name %></h1>
      <p class="lead"><%= @project.description %>  </p>
      <div><%= link_to "Edit", edit_project_path(@project.id) %> | <%= link_to "Delete", @project, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to "All Projects", projects_path %></div>
      </br>


</div>
<div class="col-md-2"></div>
<div class="col-md-3">
</br>
        <table class="table">
        <thead>

        </thead>
        <tbody>
        <tr>
          <td><b>Status:</b></td><td> <%= @project.status %></td>
        <%if !@project.team.nil?%>
          <td><b>Team:</b></td><td> <%= link_to @project.team.name, team_path(@project.team.id) %></td>
        <%end%>
        </tr>

        </tbody>
        </table>

</div>
<div class="col-md-2"></div>
</div>

<div class="row">
<div class="col-md-1"></div>
<div class="col-md-3">
  

<h4> CREATE A TASK </h4>

<%=render partial: "shared/error_messages", locals: {new_object: @task}%>

<%= bootstrap_form_for(@task, layout: :inline) do |f| %>

<table class="table">
    <thead>
    <tr>
    <th>Field</th>
    <th>Value </th>
    </tr>
</thead>

<tbody>
    <tr><td>Item</td><td><%= f.text_area :description, hide_label: true  %></td></tr>
    <tr><td>Due</td><td><%= f.date_field :due_date, hide_label: true  %></td></tr>
    <tr><td>Assignee</td><td><%= f.collection_select(:assignee_id, User.all, :id, :name, {hide_label: true, include_blank: true}) %></td></tr>
    <tr><td>Priority</td><td><%= f.select :priority, options_for_select([ "Low", "Medium", "High"]), {hide_label: true} %></td></tr>
    <tr><td>Status</td><td><%= f.select :status, options_for_select(["Planned", "In Progress", "Complete"]), {hide_label: true} %></td></tr>
    <tr><td></td><td><%= f.submit "Create", class: "btn btn-primary"  %> </td></tr>
        

    <%= f.hidden_field :project_id, value: @project.id %>
    <%= f.hidden_field :creator_id, value: current_user.id %>
    <%= f.hidden_field :created_location, value: "project" %>
  

      </tbody>
      </table>

<% end %>
</div>


<div class="col-md-6">



<h4>OPEN TASKS </h4>


<% if @incomplete_tasks == [] %>
 <i> <%= "The project has no incomplete tasks" %></i>
<% else %>
<table class="table">
      <thead>
          <tr>
          <th>Task</th>
          <th>Assigned To</th>
          <th>Due Date</th>
          <th>Status</th>
          </tr>
      </thead>

      <tbody>
      <% @incomplete_tasks.each do |t| %>
          <tr>
          <td><%=  link_to t.description, task_path(t.id) %></td>
          <td><%=  link_to t.assignee.name, user_path(t.assignee.id) %></td>
          <td><%=  t.due_date %></td>
          <td><%=  t.status %></td>
          </tr>
      <% end %> 
      </tbody>
      </table>

  <% end %>



  <br></br>


  
<% if @completed_tasks != [] %>
    <h4>COMPLETE</h4>


    <table class="table">
        <thead>
          <tr>
            <th>Task</th>
            <th>Assigned To</th>
            <th>Completed</th>
            <th>Status</th>
          </tr>
        </thead>

        <tbody>
        <% @completed_tasks.each do |t| %>
            <tr>
            <td><%=  link_to t.description, task_path(t.id) %></td>
            <td><%=  link_to t.assignee.name, user_path(t.assignee.id) %></td>
            <td><%=  t.date %></td>
            <td><%=  t.status %></td>
            </tr>
        <% end %> 
      </tbody>
      </table>
<% end %> 





</div>


<div class="col-md-1">
</div>
</div>