config/routes.rb
Rails.application.routes.draw do
resources :users, only: [:show, :new, :create, :edit, :update, :destroy] 
resources :teams
resources :tasks do
    member do
        patch :completed
    end
end
resources :projects
resources :comments, only: [:show, :new, :create]
resources :userteams, only: [:new, :create, :destroy]
  
get "/", to: "users#home", as: "home"
get "/login", to: "sessions#login"
post "/login", to: "sessions#process_login"
get "/logout", to: "sessions#logout"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Team</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('OverProject.png') %>
    
  </head>

  <body>
    <header>
    <div class="logo">
      <%= link_to (image_tag("boxed-artwork3.png", width: "150px")), home_path %>
    </div>
      <nav>
        <ul class="nav_links">
          <li><%=link_to "Tasks", tasks_path%></li>
          <li><%=link_to "Teams", teams_path%></li>
          <li><%= link_to "Projects", projects_path %></li>
        </ul>
      </nav>
  <%if !current_user.nil?%>
      <%=link_to "Profile", user_path(current_user)%>
      <%=link_to "Logout", logout_path%>
  <% else %>
      <%=link_to "Sign Up", new_user_path%>
      <%=link_to "Login", login_path%>
  <%end %>
    </header>

    
  

    <%= yield %>

    
  </body>
</html>